### ISSUE TITLE
use Module::CoreList::is_core($mod) instead of $Module::CoreList::version

### ISSUE THREAD

**Issue by karenetheridge** [Leont/dist-zilla-role-moduleincluder#3]
There is a function interface to Module::CoreList, which might be better than directly accessing `$version` to determine whether to include certain prereqs.

**Comment by Leont** [comment]
Sounds like a good idea. Module::CoreList didn't provide such functionality when I wrote ModuleIncluder. Have updated some of my modules but not all of them.

**Comment by Leont** [comment]
Implemented in 105ef0
